#!/usr/bin/env python3
"""Private ZEKRA-only Docker proxy: bound CPUs, retain exit evidence, remove own containers."""
import json
import hashlib
import os
from pathlib import Path
import subprocess
import sys
import time
import uuid

real = os.environ["ZEKRA_REAL_DOCKER"]
args = sys.argv[1:]
if not args or args[0] != "run":
    raise SystemExit(subprocess.call([real, *args]))

name = "zkcfa64-z21-" + uuid.uuid4().hex[:16]
label = os.environ["ZEKRA_RUN_LABEL"]
app = "unknown"
stage = "unknown"
if "scripts/circuit_input_formatter.py" in args:
    stage = "format"
    app = Path(args[args.index("-a") + 1]).name
elif "scripts/compile_circuit.py" in args:
    stage = "compile"
    app = Path(args[args.index("--input-dir") + 1]).name
else:
    stage = "groth16"
    for value in args:
        if value.endswith(":/w"):
            app = Path(value[:-3]).name
command = [
    real, "run", "--name", name, "--label", "zkcfa.zekra21.run=" + label,
    "--network", "none",
    "--cpus", os.environ["ZEKRA_CPUS"],
    "--env", "OMP_NUM_THREADS=" + os.environ["ZEKRA_THREADS"],
    "--env", "OMP_DYNAMIC=FALSE",
    *[value for value in args[1:] if value != "--rm"],
]
started = time.time()
rc = subprocess.call(command)
record = {
    "application": app, "stage": stage, "container": name,
    "docker_exit_code": rc, "wall_s": round(time.time() - started, 3),
}
if stage == "groth16":
    for value in args:
        if value.endswith(":/w"):
            data = Path(value[:-3])
            record["circuit_files_sha256"] = {
                file.name: hashlib.sha256(file.read_bytes()).hexdigest()
                for file in (data / "zekra.arith", data / "zekra_Sample_Run1.in") if file.exists()
            }
inspection = subprocess.run(
    [real, "container", "inspect", "--format", "{{json .State}}", name],
    text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
)
if inspection.returncode == 0:
    state = json.loads(inspection.stdout)
    record["state"] = {key: state.get(key) for key in (
        "Status", "Running", "OOMKilled", "ExitCode", "Error", "StartedAt", "FinishedAt"
    )}
    # This exact name was just generated by this invocation.
    subprocess.run([real, "container", "rm", name], stdout=subprocess.DEVNULL,
                   stderr=subprocess.DEVNULL, check=False)
else:
    record["inspection_unavailable"] = True
with Path(os.environ["ZEKRA_DOCKER_EVENTS"]).open("a", encoding="utf-8") as stream:
    stream.write(json.dumps(record, sort_keys=True) + "\n")
raise SystemExit(rc if rc >= 0 else 128 - rc)
